print ("Hello World!")
name = input ("Zadejte své jméno: ")
print()
print ("-----------------------------------------")
print ("Name: " + name)
print("Obor: IT")
print("Zájmy: Programování, sport, hudba")
print ("-----------------------------------------")
print()